#! /bin/bash

R=$1
D=1.0
C=0.1
MOCDE=mocde-randbest1
NAME=mocde #-$D-$C
FUNCTIONS="zdt4 dtlz1 dtlz3"
#FUNCTIONS="zdt* dtlz* uf*"

./test/test.py -n $NAME -r $R -p 100 -d $D -c $C -l 0 --exe ./bin/$MOCDE $FUNCTIONS

